version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Starting build

  build:
    commands:
      - echo Building Docker image
      - docker build -t calculator-application .

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
